--- Makefile	2013-09-22 13:47:48.000000000 +0900
+++ /Users/argon/3dcg2/cg_gcc/prj/Makefile	2013-09-22 12:52:30.000000000 +0900
@@ -9,10 +9,10 @@
 OBJECT=$(TARGET).o
 
 
-CC = gcc -g -w -O3 -fno-for-scope  -fthis-is-variable -I $(INCDIR)
+CC = g++ -g -w -O3 -fno-for-scope  -fthis-is-variable -I $(INCDIR)
 #CC = gcc -g -w  -fthis-is-variable
-CCFLAG = `gtk-config --cflags`
-LINKFLAG = `gtk-config --libs` -lXpm -lgdk_imlib -lXpm -ljpeg -lpng -ltiff -lz -lgif -lm -lstdc++
+CCFLAG = `pkg-config --cflags opencv`
+LINKFLAG = `pkg-config --libs opencv` -lm
 COMPILE = $(CC) $(CCFLAG)
 LINK = $(CC) $(LINKFLAG) 
 
